services:
  - type: web
    name: passamoz
    runtime: python
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.3"
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: EMAIL_USE_TLS
        value: "True"
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: PASSAMOZ_ADMIN_EMAIL
        sync: false
      - key: EMAIL_TIMEOUT
        value: "20"
